In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('/Users/liukebing/Desktop/Data Analysis/Data/Brazilian E-commerce Dataset by Olist/olist_decision_tree.csv')

In [5]:
clusters=pd.read_csv('/Users/liukebing/Desktop/Data Analysis/Data/Brazilian E-commerce Dataset by Olist/olist_rfm_with_clusters.csv')

In [7]:
df1 = pd.merge(clusters,df, on='customer_unique_id', how='left')

In [8]:
df1.head()

,customer_unique_id,recency,frequency,monetary,cluster,delivery_delay,review_score,freight_ratio,price,freight_value,is_delayed,is_high_score,is_repurchased
0,0000366f3b9a7992bf8c76cfdf3221e2,111,1,129.90,1,-4.0,5.0,0.084567,129.90,12.00,0.0,1.0,0.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,114,1,18.90,1,-4.0,4.0,0.304892,18.90,8.29,0.0,1.0,0.0
2,0000f46a3911fa3c0805444483337064,536,1,69.00,0,-1.0,3.0,0.199722,69.00,17.22,0.0,0.0,0.0
3,0000f6ccb0745a6a4b88665a16c9f078,320,1,25.99,0,-11.0,4.0,0.404172,25.99,17.63,0.0,1.0,0.0
4,0004aac84e0df4da2b147fca70cf8255,287,1,180.00,0,-7.0,5.0,0.085784,180.00,16.89,0.0,1.0,0.0

In [9]:
df1['delivery_delay'].mean()

np.float64(-11.225387762649962)

In [11]:
df1[df1['cluster']==1]['delivery_delay'].mean()

np.float64(-10.939135116614866)

In [12]:
df1[df1['cluster']==2]['delivery_delay'].mean()

np.float64(-11.81856446610545)

In [13]:
df1[df1['cluster']==3]['delivery_delay'].mean()

np.float64(-11.35438413361169)

In [14]:
df1[df1['cluster']==0]['delivery_delay'].mean()

np.float64(-11.400927499495925)

In [15]:
df1['price'].mean()

np.float64(126.01674425054892)

In [16]:
df1[df1['cluster']==2]['price'].mean()

np.float64(80.21849579087284)

In [17]:
df1[df1['cluster']==1]['price'].mean()

np.float64(108.80844055105587)

In [18]:
df1[df1['cluster']==0]['price'].mean()

np.float64(107.47694202021948)

In [19]:
df1[df1['cluster']==3]['price'].mean()

np.float64(1044.8067901878915)

In [20]:
df1['freight_value'].mean()

np.float64(20.099653183866867)

In [21]:
df1[df1['cluster']==2]['freight_value'].mean()

np.float64(18.14323216659282)

In [22]:
df1[df1['cluster']==1]['freight_value'].mean()

np.float64(20.063656984853303)

In [23]:
df1[df1['cluster']==0]['freight_value'].mean()

np.float64(19.012513033209483)

In [37]:
df1[df1['cluster']==3]['freight_value'].mean()

np.float64(49.78548016701461)

In [40]:
df1['review_score'].mean()

np.float64(4.141414258951117)

In [42]:
df1[df1['cluster']==2]['review_score'].mean()

np.float64(3.7102049960793098)

In [44]:
df1[df1['cluster']==1]['review_score'].mean()

np.float64(4.1821560423332516)

In [46]:
df1[df1['cluster']==0]['review_score'].mean()

np.float64(4.208699434536755)

In [47]:
df1[df1['cluster']==3]['review_score'].mean()

np.float64(4.074855034264628)

In [26]:
items=pd.read_csv('/Users/liukebing/Desktop/Data Analysis/Data/Brazilian E-commerce Dataset by Olist/olist_order_items_dataset.csv')

In [27]:
df2=pd.read_csv('/Users/liukebing/Desktop/Data Analysis/Data/Brazilian E-commerce Dataset by Olist/olist_delay_review_freight.csv')

In [28]:
df3=pd.merge(df2,items,how='left',on='order_id')

In [29]:
df3.head()

,customer_unique_id,order_id,delivery_delay,review_score,freight_ratio,price_x,freight_value_x,is_delayed,is_high_score,is_repurchased,order_item_id,product_id,seller_id,shipping_limit_date,price_y,freight_value_y
0,0000366f3b9a7992bf8c76cfdf3221e2,e22acc9c116caa3f2b7121bbb380d08e,-4.0,5.0,0.084567,129.90,12.00,0.0,1.0,0,1,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,2018-05-15 11:11:18,129.90,12.00
1,0000b849f77a49e4a4ce2b2a4ca5be3f,3594e05a005ac4d06a72673270ef9ec9,-4.0,4.0,0.304892,18.90,8.29,0.0,1.0,0,1,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,2018-05-11 17:56:33,18.90,8.29
2,0000f46a3911fa3c0805444483337064,b33ec3b699337181488304f362a6b734,-1.0,3.0,0.199722,69.00,17.22,0.0,0.0,0,1,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,2017-03-15 21:05:03,69.00,17.22
3,0000f6ccb0745a6a4b88665a16c9f078,41272756ecddd9a9ed0180413cc22fb6,-11.0,4.0,0.404172,25.99,17.63,0.0,1.0,0,1,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,2017-10-18 21:49:17,25.99,17.63
4,0004aac84e0df4da2b147fca70cf8255,d957021f1127559cd947b62533f484f7,-7.0,5.0,0.085784,180.00,16.89,0.0,1.0,0,1,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,2017-11-22 20:06:52,180.00,16.89

In [30]:
basket_size = df3.groupby('customer_unique_id')['order_item_id'].count()

In [31]:
df3 = df3.merge(basket_size.rename('basket_size'), on='customer_unique_id', how='left')

In [32]:
df3.head()

,customer_unique_id,order_id,delivery_delay,review_score,freight_ratio,price_x,freight_value_x,is_delayed,is_high_score,is_repurchased,order_item_id,product_id,seller_id,shipping_limit_date,price_y,freight_value_y,basket_size
0,0000366f3b9a7992bf8c76cfdf3221e2,e22acc9c116caa3f2b7121bbb380d08e,-4.0,5.0,0.084567,129.90,12.00,0.0,1.0,0,1,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,2018-05-15 11:11:18,129.90,12.00,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,3594e05a005ac4d06a72673270ef9ec9,-4.0,4.0,0.304892,18.90,8.29,0.0,1.0,0,1,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,2018-05-11 17:56:33,18.90,8.29,1
2,0000f46a3911fa3c0805444483337064,b33ec3b699337181488304f362a6b734,-1.0,3.0,0.199722,69.00,17.22,0.0,0.0,0,1,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,2017-03-15 21:05:03,69.00,17.22,1
3,0000f6ccb0745a6a4b88665a16c9f078,41272756ecddd9a9ed0180413cc22fb6,-11.0,4.0,0.404172,25.99,17.63,0.0,1.0,0,1,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,2017-10-18 21:49:17,25.99,17.63,1
4,0004aac84e0df4da2b147fca70cf8255,d957021f1127559cd947b62533f484f7,-7.0,5.0,0.085784,180.00,16.89,0.0,1.0,0,1,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,2017-11-22 20:06:52,180.00,16.89,1

In [34]:
print(df3[['basket_size', 'is_repurchased']].corr())

                basket_size  is_repurchased
basket_size        1.000000        0.626765
is_repurchased     0.626765        1.000000

In [36]:
df3.describe()

,delivery_delay,review_score,freight_ratio,price_x,freight_value_x,is_delayed,is_high_score,is_repurchased,order_item_id,price_y,freight_value_y,basket_size
count,98733.000000,97982.000000,98741.000000,98741.000000,98741.000000,98733.000000,97982.000000,98741.000000,98741.000000,98741.000000,98741.000000,98741.000000
mean,-11.353235,4.066645,0.213058,120.762385,19.932504,0.066644,0.764048,0.235586,1.197304,120.788808,19.925741,1.394608
std,10.076540,1.356059,0.129271,183.533974,15.602356,0.249406,0.424594,0.424367,0.712373,183.715203,15.596745,1.134104
min,-146.000000,1.000000,0.000000,0.850000,0.000000,0.000000,0.000000,0.000000,1.000000,0.850000,0.000000,1.000000
25%,-16.000000,4.000000,0.117870,39.900000,13.110000,0.000000,1.000000,0.000000,1.000000,39.900000,13.110000,1.000000
50%,-12.000000,5.000000,0.187582,75.000000,16.240000,0.000000,1.000000,0.000000,1.000000,75.000000,16.230000,1.000000
75%,-7.000000,5.000000,0.282000,134.900000,21.120000,0.000000,1.000000,0.000000,1.000000,134.900000,21.120000,1.000000
max,188.000000,5.000000,0.955451,6735.000000,409.680000,1.000000,1.000000,1.000000,21.000000,6735.000000,409.680000,21.000000

In [52]:
df4=df2.dropna()

In [54]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85932 entries, 0 to 86529
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_unique_id  85932 non-null  object
 1   order_id            85932 non-null  object
 2   delivery_delay      85932 non-null  float64
 3   review_score        85932 non-null  float64
 4   freight_ratio       85932 non-null  float64
 5   price               85932 non-null  float64
 6   freight_value       85932 non-null  float64
 7   is_delayed          85932 non-null  float64
 8   is_high_score       85932 non-null  float64
 9   is_repurchased      85932 non-null  int64
dtypes: float64(7), int64(1), object(2)
memory usage: 7.2+ MB

In [55]:
df4.to_csv('cleaned_delay_review_freight.csv', index=False)